server {
    listen 80;

    location / { #serves your static frontend from root folder,default files index.html
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html; #if requested file exists serve it else return index.html bc otherwise youd get 404 errors on refresh
    }
    #backend api proxying blocks
    #All of these are forwarded to your backend server
    location /print-jobs { 
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /users {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /login {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
    }

    location /register {
        proxy_pass http://backend:5000;
        proxy_set_header Host $host;
    }
}