services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env #load en var from .env file
    environment:       #env variables for our backend, eg. accessed using process.env.DB
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}  #key used for jwt token signing
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
    depends_on:
      - postgres
    volumes:
      - ./backend/uploads:/app/uploads  #uploaded file persistence, files stored in /app/uploads path of container mapped to /backend/uploads of current folder of our computer or vps

  frontend:
    build:
      context: ./frontend #dockerfile location
      args:
        VITE_API_URL: https://printflow.top
    depends_on:
      - backend #start backend container before frontend to ensure api is available when frontend starts

  postgres:       #env var postgres expects 
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data   #vol_name:container_path (named volume declaration)
      - ./backend/db:/docker-entrypoint-initdb.d  #dockers postgrees img runs the files in /docker-entrypoint-initdb.d aitomatically when db is first created
                                                  #so init.sql will be stored there
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
volumes:               #this is basically variable declaration or resource definition 
  postgres_data:       #like this project uses a volume called postgres_data
  caddy_data:
  caddy_config:
